background = #F5F5F7
foreground = #1D1D1F
cursor-color = #000000
cursor-text = #F5F5F7
selection-background = #B3D7FF
selection-foreground = #000000

palette = 0=#F5F5F7
palette = 1=#FF3B30
palette = 2=#34C759
palette = 3=#FFCC00
palette = 4=#007AFF
palette = 5=#AF52DE
palette = 6=#32ADE6
palette = 7=#1D1D1F
palette = 8=#8E8E93
palette = 9=#FF6961
palette = 10=#30D158
palette = 11=#FFD60A
palette = 12=#0A84FF
palette = 13=#BF5AF2
palette = 14=#64D2FF
palette = 15=#000000
